### PR TITLE
Added Darwin support, go module

### PR DESCRIPTION
**Pull request by tivvit**

### CODE REVIEW

**Comment by tivvit** [comment]
connected to curusarn/resh#1

**Comment by tivvit** [comment]
this may be usefull `TERM_SESSION_ID`

**Comment by curusarn** [comment]
connected to https://github.com/curusarn/resh/issues/6

**Comment by curusarn** [comment]
mostly "merged" in https://github.com/curusarn/resh/commit/fb6bb3a8ab54e1bfd1f7a953d1f5f1f272a889f8

**Pull request closed without merging**
