### PR TITLE
update go version to 1.16 and goreleaser to support M1 macOS (arm64)

### PR DESCRIPTION
**Pull request by tivvit**
closes https://github.com/curusarn/resh/issues/158

This should be sufficient for M1 MacBooks - not tested

### CODE REVIEW

**Comment by tivvit** [comment]
You can see `darwin_arm` in the goreleaser log in my repo 

[log](https://pipelines.actions.githubusercontent.com/HNPNBL2G9Zz7KFmZfrwHSjlRLLR79P4qJBD0kIlyJKoNgFvXz2/_apis/pipelines/1/runs/1/signedlogcontent/3?urlExpires=2021-06-30T15%3A39%3A07.8342772Z&urlSigningMethod=HMACV1&urlSignature=M5Xt2ka%2FWqK3W1GhrjUDRL9VogCvjtqygHdNBphnrfQ%3D)
[action](https://github.com/tivvit/resh/runs/2811415045?check_suite_focus=true)

**Comment by tivvit** [comment]
ping :)

**Comment by curusarn** [comment]
Thanks, sorry for the wait

**Comment by tivvit** [comment]
Maybe you should run the action again or release a new version because currently the install script does not fail on the check but the arm version is not published therefore the checksum validation fails.

**Comment by curusarn** [comment]
Good point. I just released a new version.

It's quite possible that `reshctl update` will still not work because it uses the (raw)install script from locally installed version to download the archive with new version. But this one-time issue should be fixed by following the instructions on the install page - i.e. running the `curl` install command or cloning and installing resh.

**Comment by tivvit** [comment]
Reinstalled it from the web and works like a charm thanks 👍

**Pull request merged**
